"""empty message

Revision ID: 45c88c501125
Revises: 4a91af90912a
Create Date: 2022-07-31 21:12:45.997387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45c88c501125"
down_revision = "4a91af90912a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "endereco", sa.Column("municipio_id", sa.BigInteger(), nullable=False)
    )
    op.drop_constraint("endereco_municipio_fkey", "endereco", type_="foreignkey")
    op.create_foreign_key(None, "endereco", "municipio", ["municipio_id"], ["id"])
    op.drop_column("endereco", "municipio")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "endereco",
        sa.Column("municipio", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "endereco", type_="foreignkey")
    op.create_foreign_key(
        "endereco_municipio_fkey", "endereco", "municipio", ["municipio"], ["id"]
    )
    op.drop_column("endereco", "municipio_id")
    # ### end Alembic commands ###
