"""empty message

Revision ID: 4a91af90912a
Revises: ab3b2b07769f
Create Date: 2022-07-30 17:23:52.284042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a91af90912a'
down_revision = 'ab3b2b07769f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login', sa.Column('acesso_id', sa.Integer(), nullable=False))
    op.drop_constraint('login_acesso_fkey', 'login', type_='foreignkey')
    op.create_foreign_key(None, 'login', 'acesso', ['acesso_id'], ['id'])
    op.drop_column('login', 'acesso')
    op.alter_column('usuario', 'endereco_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'endereco_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.add_column('login', sa.Column('acesso', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'login', type_='foreignkey')
    op.create_foreign_key('login_acesso_fkey', 'login', 'acesso', ['acesso'], ['id'])
    op.drop_column('login', 'acesso_id')
    # ### end Alembic commands ###
