"""empty message

Revision ID: ab3b2b07769f
Revises: 0a70f4b317e3
Create Date: 2022-07-30 16:29:03.910370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3b2b07769f'
down_revision = '0a70f4b317e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login', sa.Column('usuario_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'login', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'login', type_='foreignkey')
    op.drop_column('login', 'usuario_id')
    # ### end Alembic commands ###
