"""empty message

Revision ID: c1c9eb9bffc4
Revises: 
Create Date: 2022-08-04 19:27:27.965850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c9eb9bffc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('controller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=2), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('regra',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('acesso_id', sa.Integer(), nullable=False),
    sa.Column('controller_id', sa.Integer(), nullable=False),
    sa.Column('permicao', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['acesso_id'], ['acesso.id'], ),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.id'], ),
    sa.PrimaryKeyConstraint('id', 'acesso_id', 'controller_id')
    )
    op.create_table('municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('uf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uf_id'], ['estado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cep', sa.String(length=255), nullable=False),
    sa.Column('rua', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=255), nullable=False),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('municipio_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('pis', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=50), nullable=False),
    sa.Column('endereco_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('pis')
    )
    op.create_table('login',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('acesso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acesso_id'], ['acesso.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login')
    op.drop_table('usuario')
    op.drop_table('endereco')
    op.drop_table('municipio')
    op.drop_table('regra')
    op.drop_table('estado')
    op.drop_table('pais')
    op.drop_table('controller')
    op.drop_table('acesso')
    # ### end Alembic commands ###
