from source.model.acessoTable import Acesso, AcessoModel
from source.model.controllerTable import Controller, ControllerModel
from source.model.enderecoTable import Endereco, EnderecoModel
from source.model.estadoTable import Estado, EstadoModel
from source.model.loginTable import Login, LoginModel
from source.model.municipioTable import Municipio, MunicipioModel
from source.model.paisTable import Pais, PaisModel
from source.model.regraTable import Regra, RegraModel
from source.model.usuarioTable import Usuario, UsuarioModel